"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Archive, Bot, CheckCircle2, FileCheck2, FileInput, HardDrive, Play, ScanSearch, ShieldCheck, UploadCloud } from "lucide-react";
import { ReportEditor } from "./report-editor";

type Preflight = { freeGiB: number; ready: boolean; directory: string };

export function Workbench() {
  const [preflight, setPreflight] = useState<Preflight | null>(null);
  const [crawlState, setCrawlState] = useState<"idle" | "validated">("idle");
  useEffect(() => { fetch("/api/preflight").then((response) => response.json()).then(setPreflight).catch(() => setPreflight(null)); }, []);
  return <div className="wb-shell"><header className="wb-top"><div className="wb-brand"><span className="wb-mark">P</span><div><strong>SEO Workbench</strong><span>Preparación y aprobación local</span></div></div><nav style={{ marginLeft: 28, display: "flex", gap: 16 }}><Link href="/" style={{ color: "#fff", font: "600 13px/1 var(--ds-font-sans)" }}>Preparación y aprobación</Link><Link href="/editorial" style={{ color: "rgb(255 255 255 / 75%)", font: "600 13px/1 var(--ds-font-sans)" }}>Editorial</Link></nav><span className="local-pill">● Solo este equipo · 127.0.0.1</span></header><main className="wb-main"><header className="wb-heading"><div><p className="eyebrow">Piloto · Porcelanosa + Noken</p><h1>Del dato bruto a una decisión publicada</h1><p className="lede">Crawls, importaciones, clasificación, narrativa y aprobación permanecen en local. Solo un paquete curado, limitado y firmado puede avanzar al visor.</p></div><div className="wb-card preflight"><div className="preflight-head"><span className="eyebrow" style={{ margin: 0 }}>Preflight de disco</span><span className={`status-dot ${preflight?.ready ? "status-dot-ready" : ""}`} aria-hidden /></div><strong>{preflight ? `${preflight.freeGiB} GiB libres` : "Comprobando…"}</strong><small>{preflight?.ready ? "Preparado para crawls" : "Se requieren al menos 50 GiB libres"}</small></div></header>
  <section className="pipeline" aria-label="Flujo de publicación">{[["01", ScanSearch, "Adquirir", "Crawl o importación con límite y procedencia."], ["02", Bot, "Depurar", "Taxonomías, señales, IA UE y revisión."], ["03", FileCheck2, "Aprobar", "Autor y revisor deben ser distintos."], ["04", ShieldCheck, "Firmar", "Contrato, allowlist, hash y firma."], ["05", UploadCloud, "Promover", "Preview privada y aprobación GitHub."]].map(([number, Icon, title, copy]) => { const StageIcon = Icon as typeof ScanSearch; return <article className="wb-card stage" key={String(number)}><span className="stage-number">{number as string}</span><StageIcon size={20} /><h2 className="ds-h3">{title as string}</h2><p>{copy as string}</p></article>; })}</section>
  <div className="wb-grid"><div><section className="wb-card panel"><div className="panel-head"><div><p className="eyebrow">Adquisición local</p><h2>Crawls e importaciones</h2></div><span className="badge badge-good">Límite 50.000</span></div><div className="job-list"><div className="job"><span className="job-icon"><Archive size={15} /></span><div><strong>Porcelanosa · Crawl v4</strong><small>2.020 URLs · aprobado · 28 ago</small></div><span className="badge badge-good">listo</span></div><div className="job"><span className="job-icon"><Archive size={15} /></span><div><strong>Noken · Crawl v4</strong><small>11.387 URLs · aprobado · 28 ago</small></div><span className="badge badge-good">listo</span></div><div className="job"><span className="job-icon"><FileInput size={15} /></span><div><strong>Importación editorial</strong><small>82 contenidos · 4 overrides pendientes</small></div><span className="badge badge-warn">revisar</span></div></div><div className="form-row"><label className="field"><span>Proyecto</span><select className="input"><option>Porcelanosa</option><option>Noken</option></select></label><label className="field"><span>Máximo de URLs</span><input className="input" type="number" defaultValue="50000" min="1" max="50000" /></label></div><label className="field" style={{ marginTop: 9 }}><span>URL inicial autorizada</span><input className="input" defaultValue="https://www.porcelanosa.com/" /></label><button className="button button-primary" style={{ marginTop: 12 }} disabled={!preflight?.ready} onClick={() => setCrawlState("validated")}><Play size={12} style={{ verticalAlign: -2, marginRight: 5 }} />{crawlState === "validated" ? "Configuración validada" : "Validar nuevo crawl"}</button>{!preflight?.ready ? <div className="notice"><HardDrive size={13} style={{ verticalAlign: -2, marginRight: 6 }} />El crawler está bloqueado hasta disponer de 50 GiB. La UI y los importadores se pueden seguir validando.</div> : null}</section>
  <section className="wb-card panel timeline"><div className="panel-head"><div><p className="eyebrow">Trazabilidad</p><h2>Historial de preparación</h2></div></div>{[["09:42", "Clasificación completada", "96% de queries con segmento de marca e intención."], ["09:18", "Paquete Noken validado", "418 filas curadas, sin PII ni campos crudos."], ["ayer", "Crawl Porcelanosa aprobado", "Autor: María SEO · Revisor: Carlos Digital."], ["28 ago", "Snapshot técnico creado", "Hash SHA-256 registrado en el manifiesto."]].map(([time, title, copy]) => <div className="timeline-row" key={title}><time>{time}</time><span className="timeline-dot" /><div><strong>{title}</strong><p>{copy}</p></div></div>)}</section></div>
  <section className="wb-card panel"><div className="panel-head"><div><p className="eyebrow">Editor estructurado · Borrador</p><h2>Cierre ejecutivo · Agosto 2026</h2></div><span className="badge badge-warn">revisión humana</span></div><ReportEditor /><div className="contract"><strong>Puerta de publicación</strong><br />18 bloques · 5 conclusiones · 7 evidencias · 0 campos prohibidos · autor y revisor distintos. Azure OpenAI solo propone texto sobre datos ya depurados; nunca publica.</div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 14 }}><button className="button">Generar preview</button><button className="button button-primary"><CheckCircle2 size={12} style={{ verticalAlign: -2, marginRight: 5 }} />Enviar a revisión</button></div></section></div></main></div>;
}
